# Generated by Django 6.0.6 on 2026-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Contribution card title.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Contribution card description."),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Frontend icon key for the contribution card.",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Contribution",
                "verbose_name_plural": "Project Contributions",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectsHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Small label above the Projects page title.",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main hero heading for the Projects page.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Supporting hero copy for the Projects page.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projects Hero",
                "verbose_name_plural": "Projects Hero",
            },
        ),
        migrations.CreateModel(
            name="ProjectsSectionIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        choices=[
                            ("featured", "Featured Projects"),
                            ("categories", "Project Categories"),
                            ("technologies", "Technologies"),
                            ("beyond", "Beyond Projects"),
                        ],
                        help_text="Unique key for a Projects page section intro.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="Small label above the section title.",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Main section heading.", max_length=255),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="Supporting copy for the section."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projects Section Intro",
                "verbose_name_plural": "Projects Section Intros",
                "ordering": ["section_key"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Stat value, e.g. 20+, 100%.", max_length=50
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Stat label, e.g. Projects, Technologies.",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Stat",
                "verbose_name_plural": "Project Stats",
                "ordering": ["display_order", "label"],
            },
        ),
    ]
