from .knowledge_hub_admin import *
from .knowledge_theme_admin import *
from .knowledge_tag_admin import *
from .library_resource_admin import *
from .learning_video_admin import *
from .organization_admin import *
from .practical_resource_admin import *
from .research_contribution_admin import *
from .search_configuration_admin import *