# Generated by Django 6.0.6 on 2026-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactmessage_honeypot_alter_contactmessage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
