# Generated by Django 6.0.6 on 2026-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FutureFocus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Frontend icon key, e.g. healthcare, digital-health, ai, research, leadership, global",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Future Focus",
                "verbose_name_plural": "Future Focus",
                "ordering": ("display_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="JourneyHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journey Hero",
                "verbose_name_plural": "Journey Hero",
            },
        ),
        migrations.CreateModel(
            name="JourneySectionIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        choices=[("timeline", "Timeline"), ("future", "Future Vision")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("intro", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journey Section Intro",
                "verbose_name_plural": "Journey Section Intros",
                "ordering": ("section_key",),
            },
        ),
    ]
