# Generated by Django 6.0.6 on 2026-07-10 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Insights Page",
                        help_text="Administrative title for the Insights page.",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slug for the Insights page.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Marks this Insights page configuration as active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Insight Page",
                "verbose_name_plural": "Insight Pages",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="InsightPageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True, default="Insights & Perspectives", max_length=120
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main hero title for the Insights page.",
                        max_length=255,
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, help_text="Supporting hero subtitle / description."
                    ),
                ),
                (
                    "insight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight Page Hero",
                "verbose_name_plural": "Insight Page Hero",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True, default="Stay Connected", max_length=120
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Newsletter section title.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Supporting copy for the newsletter block.",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, default="Enter your email address", max_length=150
                    ),
                ),
                (
                    "button_text",
                    models.CharField(blank=True, default="Subscribe", max_length=80),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "insight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletter",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(help_text="The quote or reflection text.")),
                ("author", models.CharField(default="Awoii Bob Willy", max_length=120)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Primary category label shown on the card.",
                        max_length=120,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary or excerpt for the article.",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/insights/featured_articles/",
                    ),
                ),
                (
                    "read_time",
                    models.CharField(
                        blank=True, help_text='Example: "6 min read"', max_length=50
                    ),
                ),
                ("published_at", models.DateField(blank=True, null=True)),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="Optional external article URL."
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True,
                        help_text="Marks the article as part of the featured article section.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_articles",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Article",
                "verbose_name_plural": "Featured Articles",
                "ordering": ["display_order", "-published_at", "title"],
                "unique_together": {("insight", "slug")},
            },
        ),
        migrations.CreateModel(
            name="InsightCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight Category",
                "verbose_name_plural": "Insight Categories",
                "ordering": ["display_order", "name"],
                "unique_together": {("insight", "slug")},
            },
        ),
        migrations.CreateModel(
            name="InsightSectionIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        choices=[
                            ("featured_articles", "Featured Articles"),
                            ("categories", "Categories"),
                            ("thoughts", "Thoughts"),
                            ("quotes", "Quotes"),
                        ],
                        help_text="The section this intro belongs to.",
                        max_length=50,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, default="", max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("intro", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Controls section intro ordering where needed.",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_intros",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight Section Intro",
                "verbose_name_plural": "Insight Section Intros",
                "ordering": ["display_order", "id"],
                "unique_together": {("insight", "section_key")},
            },
        ),
        migrations.CreateModel(
            name="Thought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category label for the thought card.",
                        max_length=120,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Short reflection or excerpt."
                    ),
                ),
                ("published_at", models.DateField(blank=True, null=True)),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional external link for the full thought/article.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thoughts",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thought",
                "verbose_name_plural": "Thoughts",
                "ordering": ["display_order", "-published_at", "title"],
                "unique_together": {("insight", "slug")},
            },
        ),
    ]
