# Generated by Django 6.0.6 on 2026-07-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightHeroStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=120)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="insights.insightpagehero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight Hero Statistic",
                "verbose_name_plural": "Insight Hero Statistics",
                "ordering": ("display_order", "id"),
            },
        ),
    ]
