# Generated by Django 6.0.6 on 2026-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0002_insightherostat"),
    ]

    operations = [
        migrations.AddField(
            model_name="insightpagehero",
            name="description",
            field=models.TextField(
                blank=True, help_text="Supporting hero subtitle / description."
            ),
        ),
    ]
