# Generated by Django 6.0.6 on 2026-07-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0003_insightpagehero_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insightcategory",
            options={
                "ordering": ("display_order", "name"),
                "verbose_name": "Insight Category",
                "verbose_name_plural": "Insight Categories",
            },
        ),
        migrations.RemoveField(
            model_name="featuredarticle",
            name="read_time",
        ),
        migrations.AddField(
            model_name="featuredarticle",
            name="read_time_minutes",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="insightcategory",
            name="accent_color",
            field=models.CharField(
                default="#2563EB",
                help_text="Hex color used by the frontend.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="insightcategory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="featuredarticle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_articles",
                to="insights.insightcategory",
            ),
        ),
        migrations.AlterField(
            model_name="insightcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
