# Generated by Django 6.0.6 on 2026-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_highlight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="highlight",
            options={"ordering": ["display_order"]},
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="description",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="link",
        ),
        migrations.AddField(
            model_name="highlight",
            name="suffix",
            field=models.CharField(default="+", max_length=10),
        ),
        migrations.AddField(
            model_name="highlight",
            name="value",
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="highlight",
            name="icon",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
