# Generated by Django 6.0.6 on 2026-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_highlight_options_remove_highlight_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Technology name (e.g., React, Django, PostgreSQL)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="React icon name (e.g., FaReact)",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Primary brand color (Hex code)",
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=80, help_text="Proficiency percentage (0–100)"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
