# Generated by Django 6.0.6 on 2026-06-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_technology"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g. Healthcare, Web Development)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="React icon name (e.g. FaHospital)",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Hex color used for badges",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
