# Generated by Django 6.0.6 on 2026-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="canonical_url",
            field=models.URLField(blank=True, help_text="Optional canonical URL."),
        ),
        migrations.AddField(
            model_name="project",
            name="keywords",
            field=models.CharField(
                blank=True, help_text="Comma-separated SEO keywords.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO description (recommended: 150–160 characters).",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="SEO title (recommended: 50–60 characters).",
                max_length=70,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Open Graph image used for LinkedIn, Facebook, WhatsApp, etc.",
                null=True,
                upload_to="projects/og/",
            ),
        ),
    ]
