# Generated by Django 6.0.6 on 2026-06-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_project_canonical_url_project_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="projects/media/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail used for videos or documents.",
                        null=True,
                        upload_to="projects/media/thumbnails/",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("caption", models.TextField(blank=True)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Accessibility text.", max_length=200
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "featured_on_home",
                    models.BooleanField(
                        default=False,
                        help_text="Use this media as the preview on the Home page.",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Primary media for the Project Detail page.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="home.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Media",
                "verbose_name_plural": "Project Media",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
