# Generated by Django 6.0.6 on 2026-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_projectmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "journey_type",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("employment", "Employment"),
                            ("leadership", "Leadership"),
                            ("research", "Research"),
                            ("volunteer", "Volunteer"),
                            ("award", "Award"),
                            ("project", "Major Project"),
                            ("milestone", "Career Milestone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="journey/"),
                ),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ("-started_at", "display_order"),
            },
        ),
    ]
