# Generated by Django 6.0.6 on 2026-07-07 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnologyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Group name (e.g. Frontend, Backend, Mobile)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Technology Group",
                "verbose_name_plural": "Technology Groups",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="technology",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional technology group for portfolio display (e.g. Frontend, Backend, Data Science).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technologies",
                to="home.technologygroup",
            ),
        ),
    ]
