"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decouple import config

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z4+*m$us5+7bug@1%ii(6p!1hb5*g=e1o4xi%0&dokrzx1r*8x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


EMAIL_HOST = "smtp-relay.brevo.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = config("BREVO_LOGIN")

EMAIL_HOST_PASSWORD = config("BREVO_SMTP_KEY")

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="Awoii Bob Willy <awoiibobwilly@gmail.com>"
)

SERVER_EMAIL = DEFAULT_FROM_EMAIL

CONTACT_RECEIVER_EMAIL = config(
    "CONTACT_RECEIVER_EMAIL"
)



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "contact",
    "home",
    "django_filters",
    "research",
    "about",
    "journey",
    "projects",
    "insights",
    "hub",
    "core",
    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "config.urls"


REST_FRAMEWORK = {

    # =====================================================
    # Authentication
    # =====================================================

    # "DEFAULT_AUTHENTICATION_CLASSES": (
    #     ...
    # ),

    # =====================================================
    # Permissions
    # =====================================================

    # "DEFAULT_PERMISSION_CLASSES": (
    #     ...
    # ),

    # =====================================================
    # Filtering
    # =====================================================

    "DEFAULT_FILTER_BACKENDS": (

        "django_filters.rest_framework.DjangoFilterBackend",

        "rest_framework.filters.SearchFilter",

        "rest_framework.filters.OrderingFilter",

    ),

    # =====================================================
    # Throttling
    # =====================================================

    "DEFAULT_THROTTLE_CLASSES": (

        "rest_framework.throttling.ScopedRateThrottle",

    ),

    "DEFAULT_THROTTLE_RATES": {

        "contact": "5/minute",

        'home': '100/day',

        # "contact": "3/minute",

        # "contact_hourly": "20/hour",

        # "contact_daily": "50/day",

        # "contact": "5/hour",

        # "projects": "60/hour",

        # "anonymous": "100/hour",

    },

}


CELERY_BROKER_URL = "redis://localhost:6379/0"

CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

CELERY_ACCEPT_CONTENT = [

    "json",

]

CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = "Africa/Kampala"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

CORS_ALLOW_ALL_ORIGINS = True


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LOGGING = {

    "version": 1,

    "disable_existing_loggers": False,

    "formatters": {

        "standard": {

            "format":

            "[{asctime}] {levelname} {name}: {message}",

            "style": "{",

        },

    },

    "handlers": {

        "file": {

            "level": "INFO",

            "class": "logging.FileHandler",

            "filename": "logs/contact.log",

            "formatter": "standard",

        },

        "console": {

            "class": "logging.StreamHandler",

            "formatter": "standard",

        },

    },

    "loggers": {

        "contact": {

            "handlers": [

                "file",

                "console",

            ],

            "level": "INFO",

            "propagate": False,

        },

    },

}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ==========================================================
# Static Files
# ==========================================================

STATIC_URL = "static/"

# ==========================================================
# Media Files
# ==========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"