# Generated by Django 6.0.6 on 2026-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="about/hero/"),
                ),
                ("image_alt", models.CharField(blank=True, default="", max_length=255)),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of stat objects. Example: [{"value":"10+","label":"Years Experience"}]',
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of highlight strings or objects. Example: ["Healthcare Leadership", "Software Engineering"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Hero",
                "verbose_name_plural": "About Hero",
            },
        ),
        migrations.CreateModel(
            name="CoreValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(default="Core Values", max_length=200),
                ),
                ("section_description", models.TextField(blank=True, default="")),
                ("mission_title", models.CharField(default="Mission", max_length=150)),
                ("mission_description", models.TextField()),
                ("vision_title", models.CharField(default="Vision", max_length=150)),
                ("vision_description", models.TextField()),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of value objects. Example: [{"letter":"A","title":"Accountability","description":"..."}]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Core Values",
                "verbose_name_plural": "Core Values",
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("certification", "Certification"),
                        ],
                        default="education",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("institution", models.CharField(max_length=255)),
                ("period", models.CharField(blank=True, default="", max_length=100)),
                ("note", models.TextField(blank=True, default="")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Credential",
                "verbose_name_plural": "Credentials",
                "ordering": ["group", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalDNA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Frontend icon key, e.g. FaChartLine",
                        max_length=100,
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of short bullet highlights for this DNA pillar.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Professional DNA Item",
                "verbose_name_plural": "Professional DNA Items",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SelectedAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("year", models.CharField(blank=True, default="", max_length=20)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Selected Achievement",
                "verbose_name_plural": "Selected Achievements",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of skills under this category. Example: ["Python", "Django", "React"]',
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WhoIAm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Frontend icon key, e.g. FaUserDoctor",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Who I Am Item",
                "verbose_name_plural": "Who I Am Items",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
