# Generated by Django 6.0.6 on 2026-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSectionIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        choices=[
                            ("who_i_am", "Who I Am"),
                            ("professional_dna", "Professional DNA"),
                            ("core_values", "Core Values"),
                            ("selected_achievements", "Selected Achievements"),
                            ("credentials", "Credentials"),
                            ("skills", "Skills & Tools"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("intro", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Section Intro",
                "verbose_name_plural": "About Section Intros",
                "ordering": ["section_key"],
            },
        ),
    ]
