# Generated by Django 6.0.6 on 2026-06-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="React Icon name e.g. FaHeartbeat",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563EB", help_text="Hex colour", max_length=7
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Category",
                "verbose_name_plural": "Research Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#2563EB",
                        help_text="Hex colour used for badges.",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional React Icon name.",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Keyword",
                "verbose_name_plural": "Research Keywords",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("journal_article", "Journal Article"),
                            ("conference_paper", "Conference Paper"),
                            ("book_chapter", "Book Chapter"),
                            ("technical_report", "Technical Report"),
                            ("case_study", "Case Study"),
                            ("white_paper", "White Paper"),
                            ("research_proposal", "Research Proposal"),
                            ("dissertation", "Dissertation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("authors", models.CharField(max_length=500)),
                ("institution", models.CharField(blank=True, max_length=255)),
                ("journal", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("abstract", models.TextField()),
                (
                    "summary",
                    models.TextField(help_text="Short summary for homepage previews."),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="research/images/"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="research/papers/"
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("external_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("accepted", "Accepted"),
                            ("under_review", "Under Review"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=30,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research",
                        to="research.researchcategory",
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True,
                        related_name="research",
                        to="research.researchkeyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research",
                "verbose_name_plural": "Research",
                "ordering": ["display_order", "-year", "-created_at"],
            },
        ),
    ]
