# Generated by Django 6.0.6 on 2026-07-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="React icon name e.g. FaMicroscope",
                        max_length=100,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#2563EB",
                        help_text="Hex colour used for this area card.",
                        max_length=7,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Area",
                "verbose_name_plural": "Research Areas",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResearchInterestGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Interest Group",
                "verbose_name_plural": "Research Interest Groups",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResearchMethodologyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="React icon name e.g. FaFlask",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Methodology Group",
                "verbose_name_plural": "Research Methodology Groups",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResearchPageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(default="Research & Inquiry", max_length=120),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Page Hero",
                "verbose_name_plural": "Research Page Hero",
            },
        ),
        migrations.CreateModel(
            name="ResearchPhilosophyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="React icon name e.g. FaLightbulb",
                        max_length=100,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#2563EB",
                        help_text="Optional hex colour for UI use.",
                        max_length=7,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Philosophy Point",
                "verbose_name_plural": "Research Philosophy Points",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResearchSectionIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        choices=[
                            ("areas", "Research Areas"),
                            ("publications", "Publications"),
                            ("methodologies", "Methodologies & Tools"),
                            ("interests", "Research Interests"),
                            ("philosophy", "Research Philosophy"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("intro", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Section Intro",
                "verbose_name_plural": "Research Section Intros",
                "ordering": ["section_key"],
            },
        ),
        migrations.CreateModel(
            name="ResearchInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="research.researchinterestgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Interest",
                "verbose_name_plural": "Research Interests",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchMethodologyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="research.researchmethodologygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Methodology Item",
                "verbose_name_plural": "Research Methodology Items",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
