# Generated by Django 6.0.6 on 2026-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_researcharea_researchinterestgroup_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="researchpagehero",
            options={
                "ordering": ["-updated_at", "-id"],
                "verbose_name": "Research Page Hero",
                "verbose_name_plural": "Research Page Hero",
            },
        ),
        migrations.AlterField(
            model_name="researcharea",
            name="accent_color",
            field=models.CharField(
                default="#2563EB",
                help_text="Hex colour used by the frontend card UI.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="researcharea",
            name="description",
            field=models.TextField(
                help_text="Short but substantive description of this research area."
            ),
        ),
        migrations.AlterField(
            model_name="researchinterestgroup",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional supporting description for this research interest cluster.",
            ),
        ),
        migrations.AlterField(
            model_name="researchmethodologygroup",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional supporting description for this methodology group.",
            ),
        ),
        migrations.AlterField(
            model_name="researchphilosophypoint",
            name="accent_color",
            field=models.CharField(
                default="#2563EB",
                help_text="Optional hex colour used by the frontend card UI.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="researchphilosophypoint",
            name="description",
            field=models.TextField(
                help_text="Core principle description shown on the Research page."
            ),
        ),
        migrations.AlterField(
            model_name="researchsectionintro",
            name="eyebrow",
            field=models.CharField(
                help_text="Short section label shown above the section title.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="researchsectionintro",
            name="intro",
            field=models.TextField(
                help_text="Introductory paragraph for this section."
            ),
        ),
        migrations.AlterField(
            model_name="researchsectionintro",
            name="section_key",
            field=models.CharField(
                choices=[
                    ("areas", "Research Areas"),
                    ("publications", "Publications"),
                    ("methodologies", "Methodologies & Tools"),
                    ("interests", "Research Interests"),
                    ("philosophy", "Research Philosophy"),
                ],
                help_text="Unique page section identifier.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="researchsectionintro",
            name="title",
            field=models.CharField(
                help_text="Main heading for this section.", max_length=255
            ),
        ),
    ]
