# Generated by Django 6.0.6 on 2026-07-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eyebrow", models.CharField(default="Knowledge Hub", max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "search_placeholder",
                    models.CharField(
                        default="Search knowledge, resources, frameworks...",
                        max_length=255,
                    ),
                ),
                (
                    "hero_background",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/hub/hero/"
                    ),
                ),
                ("cta_title", models.CharField(blank=True, max_length=255)),
                ("cta_description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Knowledge Hub",
                "verbose_name_plural": "Knowledge Hub",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name.", max_length=120, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the tag."
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Tag",
                "verbose_name_plural": "Knowledge Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the knowledge theme.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Short summary displayed on cards.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the knowledge theme.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Frontend icon identifier.",
                        max_length=100,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#2563EB",
                        help_text="Theme accent color.",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/hub/themes/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Theme",
                "verbose_name_plural": "Knowledge Themes",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LearningVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("summary", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/hub/videos/thumbnails/",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("vimeo", "Vimeo"),
                            ("microsoft", "Microsoft Learn"),
                            ("coursera", "Coursera"),
                            ("linkedin", "LinkedIn Learning"),
                            ("udemy", "Udemy"),
                            ("other", "Other"),
                        ],
                        default="youtube",
                        max_length=30,
                    ),
                ),
                ("video_url", models.URLField()),
                ("presenter", models.CharField(blank=True, max_length=255)),
                ("duration_minutes", models.PositiveIntegerField(default=10)),
                ("published_at", models.DateField(blank=True, null=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_videos",
                        to="hub.knowledgetag",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_videos",
                        to="hub.knowledgetheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Video",
                "verbose_name_plural": "Learning Videos",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LibraryResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("guide", "Guide"),
                            ("white_paper", "White Paper"),
                            ("framework", "Framework"),
                            ("template", "Template"),
                            ("toolkit", "Toolkit"),
                            ("report", "Report"),
                            ("article", "Article"),
                            ("manual", "Manual"),
                            ("documentation", "Documentation"),
                            ("other", "Other"),
                        ],
                        default="article",
                        max_length=30,
                    ),
                ),
                ("summary", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/hub/library/covers/"
                    ),
                ),
                (
                    "resource_file",
                    models.FileField(
                        blank=True, null=True, upload_to="portfolio/hub/library/files/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_read_time",
                    models.PositiveIntegerField(
                        default=10, help_text="Estimated reading time in minutes."
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="library_resources",
                        to="hub.knowledgetag",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="library_resources",
                        to="hub.knowledgetheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library Resource",
                "verbose_name_plural": "Library Resources",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("healthcare", "Healthcare Organization"),
                            ("research", "Research Institution"),
                            ("technology", "Technology Company"),
                            ("learning", "Learning Platform"),
                            ("professional", "Professional Body"),
                            ("government", "Government Agency"),
                            ("ngo", "NGO"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/hub/organizations/logos/",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("country", models.CharField(blank=True, max_length=120)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="organizations", to="hub.knowledgetag"
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organizations",
                        to="hub.knowledgetheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PracticalResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("template", "Template"),
                            ("toolkit", "Toolkit"),
                            ("checklist", "Checklist"),
                            ("framework", "Framework"),
                            ("dashboard", "Dashboard"),
                            ("sop", "Standard Operating Procedure"),
                            ("policy", "Policy"),
                            ("questionnaire", "Questionnaire"),
                            ("spreadsheet", "Spreadsheet"),
                            ("other", "Other"),
                        ],
                        default="template",
                        max_length=30,
                    ),
                ),
                ("summary", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/hub/practical_resources/thumbnails/",
                    ),
                ),
                (
                    "resource_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/hub/practical_resources/files/",
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Optional version number.", max_length=30
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="practical_resources",
                        to="hub.knowledgetag",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="practical_resources",
                        to="hub.knowledgetheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practical Resource",
                "verbose_name_plural": "Practical Resources",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResearchContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("thesis", "Thesis"),
                            ("dissertation", "Dissertation"),
                            ("technical_report", "Technical Report"),
                            ("case_study", "Case Study"),
                            ("white_paper", "White Paper"),
                            ("research_report", "Research Report"),
                            ("other", "Other"),
                        ],
                        default="journal",
                        max_length=30,
                    ),
                ),
                ("summary", models.TextField()),
                ("abstract", models.TextField(blank=True)),
                (
                    "publication",
                    models.CharField(
                        blank=True,
                        help_text="Journal, conference or publisher.",
                        max_length=255,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/hub/research/covers/",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/hub/research/documents/",
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("doi", models.CharField(blank=True, max_length=120)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="research_contributions",
                        to="hub.knowledgetag",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="research_contributions",
                        to="hub.knowledgetheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Contribution",
                "verbose_name_plural": "Research Contributions",
                "ordering": ["display_order", "-publication_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="SearchConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display ordering."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Controls visibility."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "placeholder",
                    models.CharField(
                        default="Search knowledge, resources, videos...", max_length=255
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Search the Knowledge Hub", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "popular_searches",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated search suggestions.",
                        max_length=500,
                    ),
                ),
                (
                    "empty_state_title",
                    models.CharField(default="Start Exploring", max_length=255),
                ),
                (
                    "empty_state_message",
                    models.TextField(
                        blank=True,
                        default="Search across resources, research, videos, toolkits and organizations.",
                    ),
                ),
                (
                    "no_results_title",
                    models.CharField(default="No Results Found", max_length=255),
                ),
                (
                    "no_results_message",
                    models.TextField(
                        blank=True,
                        default="Try a different keyword or browse knowledge themes.",
                    ),
                ),
                (
                    "knowledge_hub",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_configuration",
                        to="hub.knowledgehub",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Configuration",
                "verbose_name_plural": "Search Configuration",
            },
        ),
    ]
